spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root123456
  graphql:
    graphiql:
      enabled: true #Whether the default GraphiQL UI is enabled.
logging:
  level:
    org:
      springframework:
        jdbc: debug
